// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cegewkyparolhwoisckv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZ2V3a3lwYXJvbGh3b2lzY2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDQwNjksImV4cCI6MjA2OTAyMDA2OX0.DQY0dZl9xLQ_RqHkqib0JB76D-flYj_w0pO6PjGOaS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});